spring.application.name=Jrpesados
# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5479/jrpesados_db
spring.datasource.username=admin
spring.datasource.password=JRP#92!wL_z8$Kq26
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate - Cria as tabelas automaticamente para você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# JWT Secret (Usada no seu TokenService)
api.security.token.secret=${JWT_SECRET:minha-senha-secreta-muito-forte}

# SSX Tracking API
ssx.api.baseUrl=https://integration.systemsatx.com.br
ssx.api.login=integracaojrpesados@ssx.com
ssx.api.password=123456
ssx.api.hashAuth=EF354420-B1DD-4F4B-A9B4-9ADF6B0337CC

# Configuracoes de E-mail (SMTP)
# Preencha aqui para enviar o codigo de verdade para o e-mail do cliente
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=SEU_EMAIL@gmail.com
spring.mail.password=SUA_SENHA_DE_APP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
